# SPDX-FileCopyrightText: 2024 Luca Bretting <luca.bretting@fau.de>
#
# SPDX-License-Identifier: MIT
[versions]
activityCompose = "1.9.3"
# @pin incompatible otherwise
agp = "8.6.0"
benmanes-versions = "0.51.0"
composeBom = "2024.10.01"
coreKtx = "1.15.0"
cyclonedx = "1.10.0"
espressoCore = "3.6.1"
junit = "4.13.2"
junitVersion = "1.2.1"
koin = "4.0.0"
kotlin = "2.0.21"
ktfmt = "0.20.1"
lifecycleRuntimeKtx = "2.8.7"
versioncatalogueupdate = "0.8.5"
rust-android = "0.9.4"
jna = "5.15.0"
timber = "5.0.1"
compose-navigation = "2.8.0"


[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
jackwharton-timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
jna = { group = "net.java.dev.jna", name = "jna", version.ref = "jna" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
com-github-benmanes-versions = { id = "com.github.ben-manes.versions", version.ref = "benmanes-versions" }
com-ncorti-ktfmt-gradle = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
nl-littlerobots-versioncatalogueupdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versioncatalogueupdate" }
org-cyclonedx-bom = { id = "org.cyclonedx.bom", version.ref = "cyclonedx" }
android-library = { id = "com.android.library", version.ref = "agp" }
rust-android = { id = "org.mozilla.rust-android-gradle.rust-android", version.ref = "rust-android" }